In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Prices.csv")

In [3]:
df

   Price
0    110
1    105
2    115
3    120
4    110
5    130
6    150
7    100
8    105

# Normalization

In [7]:
min_Price = df.Price.min()
max_Price = df.Price.max()

In [8]:
min_Price

100

In [9]:
max_Price

150

In [10]:
df['Price_normalization_manual'] = (df.Price - min_Price ) / (max_Price - min_Price)

In [11]:
df

   Price  Price_normalization_manual
0    110                         0.2
1    105                         0.1
2    115                         0.3
3    120                         0.4
4    110                         0.2
5    130                         0.6
6    150                         1.0
7    100                         0.0
8    105                         0.1

In [12]:
from sklearn.preprocessing import MinMaxScaler
mmx = MinMaxScaler()

In [13]:
df['Price_normalization_sklearn'] = mmx.fit_transform(df[['Price']])

In [14]:
df

   Price  Price_normalization_manual  Price_normalization_sklearn
0    110                         0.2                          0.2
1    105                         0.1                          0.1
2    115                         0.3                          0.3
3    120                         0.4                          0.4
4    110                         0.2                          0.2
5    130                         0.6                          0.6
6    150                         1.0                          1.0
7    100                         0.0                          0.0
8    105                         0.1                          0.1

# Standardization

In [15]:
mean_Price = df.Price.mean()
std_dof = df.Price.std(ddof=0)

In [16]:
df['Price_stanardization_manual'] = (df['Price'] - mean_Price) / std_dof

In [17]:
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual
0,110,0.2,0.2,-0.416356
1,105,0.1,0.1,-0.757011
2,115,0.3,0.3,-0.075701
3,120,0.4,0.4,0.264954
4,110,0.2,0.2,-0.416356
5,130,0.6,0.6,0.946264
6,150,1.0,1.0,2.308884
7,100,0.0,0.0,-1.097666
8,105,0.1,0.1,-0.757011

In [18]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()

In [19]:
df['Price_stanardization_sklearn'] = scaler.fit_transform(df[['Price']])

In [20]:
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual,Price_stanardization_sklearn
0,110,0.2,0.2,-0.416356,-0.416356
1,105,0.1,0.1,-0.757011,-0.757011
2,115,0.3,0.3,-0.075701,-0.075701
3,120,0.4,0.4,0.264954,0.264954
4,110,0.2,0.2,-0.416356,-0.416356
5,130,0.6,0.6,0.946264,0.946264
6,150,1.0,1.0,2.308884,2.308884
7,100,0.0,0.0,-1.097666,-1.097666
8,105,0.1,0.1,-0.757011,-0.757011

# Log transformation

In [21]:
import numpy as np

In [22]:
df['Price_log transformation_np'] = np.log1p(df[['Price']])

In [23]:
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual,Price_stanardization_sklearn,Price_log transformation_np
0,110,0.2,0.2,-0.416356,-0.416356,4.709530
1,105,0.1,0.1,-0.757011,-0.757011,4.663439
2,115,0.3,0.3,-0.075701,-0.075701,4.753590
3,120,0.4,0.4,0.264954,0.264954,4.795791
4,110,0.2,0.2,-0.416356,-0.416356,4.709530
5,130,0.6,0.6,0.946264,0.946264,4.875197
6,150,1.0,1.0,2.308884,2.308884,5.017280
7,100,0.0,0.0,-1.097666,-1.097666,4.615121
8,105,0.1,0.1,-0.757011,-0.757011,4.663439

In [24]:
from sklearn.preprocessing import FunctionTransformer

In [25]:
lt = FunctionTransformer(np.log1p)

In [26]:
df['Price_log transformation_sklearn'] = lt.fit_transform(df[['Price']])
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual,Price_stanardization_sklearn,Price_log transformation_np,Price_log transformation_sklearn
0,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530
1,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439
2,115,0.3,0.3,-0.075701,-0.075701,4.753590,4.753590
3,120,0.4,0.4,0.264954,0.264954,4.795791,4.795791
4,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530
5,130,0.6,0.6,0.946264,0.946264,4.875197,4.875197
6,150,1.0,1.0,2.308884,2.308884,5.017280,5.017280
7,100,0.0,0.0,-1.097666,-1.097666,4.615121,4.615121
8,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439

# Robust Scaler

In [27]:
from sklearn.preprocessing import RobustScaler
robust_scaler = RobustScaler()
df['Price_Robust Scaled'] = robust_scaler.fit_transform(df[['Price']])

In [28]:
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual,Price_stanardization_sklearn,Price_log transformation_np,Price_log transformation_sklearn,Price_Robust Scaled
0,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530,0.000000
1,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439,-0.333333
2,115,0.3,0.3,-0.075701,-0.075701,4.753590,4.753590,0.333333
3,120,0.4,0.4,0.264954,0.264954,4.795791,4.795791,0.666667
4,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530,0.000000
5,130,0.6,0.6,0.946264,0.946264,4.875197,4.875197,1.333333
6,150,1.0,1.0,2.308884,2.308884,5.017280,5.017280,2.666667
7,100,0.0,0.0,-1.097666,-1.097666,4.615121,4.615121,-0.666667
8,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439,-0.333333

# Max Absolute Scaler

In [29]:
from sklearn.preprocessing import MaxAbsScaler
maxabs_scaler = MaxAbsScaler()
df['Price_MaxAbs Scaled'] = maxabs_scaler.fit_transform(df[['Price']])

In [30]:
df

,Price,Price_normalization_manual,Price_normalization_sklearn,Price_stanardization_manual,Price_stanardization_sklearn,Price_log transformation_np,Price_log transformation_sklearn,Price_Robust Scaled,Price_MaxAbs Scaled
0,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530,0.000000,0.733333
1,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439,-0.333333,0.700000
2,115,0.3,0.3,-0.075701,-0.075701,4.753590,4.753590,0.333333,0.766667
3,120,0.4,0.4,0.264954,0.264954,4.795791,4.795791,0.666667,0.800000
4,110,0.2,0.2,-0.416356,-0.416356,4.709530,4.709530,0.000000,0.733333
5,130,0.6,0.6,0.946264,0.946264,4.875197,4.875197,1.333333,0.866667
6,150,1.0,1.0,2.308884,2.308884,5.017280,5.017280,2.666667,1.000000
7,100,0.0,0.0,-1.097666,-1.097666,4.615121,4.615121,-0.666667,0.666667
8,105,0.1,0.1,-0.757011,-0.757011,4.663439,4.663439,-0.333333,0.700000

In [31]:
df.to_excel('scaled prices.xlsx', index=False)
print("scaled prices.xlsx' has been generated.")

scaled prices.xlsx' has been generated.